Awiednoor/issue5
RCDD-202203-TUR-BEW/backend-capstone-turkey-lets-share pull request #18
Opened 2022-07-25 13:55 UTC by awiednoor

### Created initial project structure:

Listed below are the contents of each folder:
**middleware** : all the middleware for all routes
**config** : definitions for default configurations ex:pasport.js
**__test__**: API tests
**routes, views, controllers, models** : organizes the routes and their functionalities and models according to the MVC structure
**services**: any additional services to run on the server ex: logging
**docs**: API documentation

2022-07-25 15:45 UTC, khaldarov requested changes
- `npm` must not be used: directory must not have a `package-lock.json` file, only `yarn` and `yarn.lock`.
- File names (postModel) in some folders (models) _might_ not include the folder's name, but not too necessary.
Other than that, looks good for now.

2022-07-25 16:06 UTC, khaldarov reviewed
Looks great, thanks.

2022-07-25 16:10 UTC, khaldarov approved these changes

2022-07-26 06:57 UTC, halitbatur approved these changes

2022-07-26 06:57 UTC, halitbatur commented
Looks good!

2022-07-26 09:35 UTC, merged