Aydin nilay/issue26
RCDD-202203-TUR-BEW/backend-capstone-turkey-lets-share pull request #42
Opened 2022-08-12 20:47 UTC by niloaydin

**`getProducts` function in the controller**
Created a function which gets all the products if there is no query. If there is a query the function returns the output accordingly. 

Merged my branch with dev branch.

In the `app.js` created a constant where i combine `Public_Auth_routes` with `Public_Routes` and add the new variable on jwt middleware so that it wouldn't run authentication on public paths.

Commented out user tests and some test in auth because it prevent me from pushing my code.

Created a swagger for the same functionality.

2022-08-13 01:29 UTC, khatibAmjad approved these changes

2022-08-14 14:07 UTC, khatibAmjad requested changes

2022-08-14 14:07 UTC, khatibAmjad commented on src/docs/product.yaml
> +            parameters:
Can you put the enums of the parameters here please

2022-08-14 14:16 UTC, halitbatur approved these changes
Just do the changes Amjad requested and its ready to go

2022-08-14 19:15 UTC, khatibAmjad commented on src/docs/product.yaml
> +paths:
can you change this file's name to be like the controller's name `getProducts`

2022-08-15 15:22 UTC, khatibAmjad approved these changes

2022-08-17 17:37 UTC, merged