UPDATE /profile/address endpoint
RCDD-202203-TUR-BEW/backend-capstone-turkey-lets-share pull request #60
Opened 2022-08-17 18:40 UTC by awiednoor

- User can add a new address to address array
- User can delete an existing address
- User can update an existing address
- Address is validated before updation

2022-08-18 14:55 UTC, khatibAmjad approved these changes

2022-08-18 14:57 UTC, halitbatur approved these changes

2022-08-18 14:57 UTC, halitbatur commented on src/controllers/user.js
> +  const User = await UserModel.findOne({ _id: req.user.userId });
okay the variable name here shoulnd't be capitalized it should be camelCased

2022-08-18 15:05 UTC, khaldarov requested changes

2022-08-18 15:05 UTC, khaldarov commented on src/controllers/user.js
> +      if (operation === 'update') {
I tried to update a current address, and here's the outcome:
- This was the address we already had:
![Screenshot from 2022-08-18 17-45-48](https://user-images.githubusercontent.com/102853969/185428473-58a6356f-9fca-46c1-96a4-d4765c6c37dd.png)
- I tried to change it, and this is what I sent:
![Screenshot from 2022-08-18 17-45-51](https://user-images.githubusercontent.com/102853969/185428761-e32be6a9-70bc-4155-9cd2-387c89e2699d.png)
- I received a "address added," but it was added as a `null`, let alone the fact that it should've been an update.
- And this is what one receives when sends in the example:
![Screenshot from 2022-08-18 17-47-41](https://user-images.githubusercontent.com/102853969/185429164-bf39713b-e9be-4a1c-adb7-dc5aecbcaef3.png)

2022-08-19 10:01 UTC, khaldarov requested changes
- The docs are missing the `/api/user` part.
- A `title` field _could_ be added to the `addressSchema` to make the errors or messages easier to show. `title` might be "home" or "work," maybe. I should've done that already, sorry for that. Following that,
- When an address is deleted, it might show a `${title} address has be deleted`

### According to the documentation
- it doesn't add an address,
- it doesn't delete an address:
![Screenshot from 2022-08-19 12-40-39](https://user-images.githubusercontent.com/102853969/185592500-7ca7e331-3388-45bb-856b-4fa8a7273c91.png)
- it doesn't update an address:
![Screenshot from 2022-08-19 12-42-10](https://user-images.githubusercontent.com/102853969/185592579-03da317c-42bd-483f-b08f-1408cb030afd.png)

### Its format
- should not be like this:
![Screenshot from 2022-08-19 12-43-17](https://user-images.githubusercontent.com/102853969/185593055-0fee1b46-1488-44fe-8db7-771138d2a836.png)
- but should be like this:
![Screenshot from 2022-08-19 12-43-29](https://user-images.githubusercontent.com/102853969/185593161-48feae70-ac50-4a26-abc9-1476f0af1593.png)

It's taking a lot of time, I assume. Also, I can work on this. We can leave it for a later time if you wish.

2022-08-19 10:13 UTC, khaldarov reviewed
Okay so after a test on Postman:
- Adding an address this way (which is the correct way), giving the correct message only adds a null:
![Screenshot from 2022-08-19 13-05-16](https://user-images.githubusercontent.com/102853969/185596851-7f755875-f5c2-402c-ae48-73a28af54c4c.png)
- Adding an address in this format does work:
![Screenshot from 2022-08-19 13-07-44](https://user-images.githubusercontent.com/102853969/185596992-b3fdc212-4f64-40af-a5b2-94792fa96dc5.png)
- Deleting that address doesn't work:
![Screenshot from 2022-08-19 13-06-59](https://user-images.githubusercontent.com/102853969/185597076-aff3becd-9302-42ad-aa5b-11203baa0819.png)

2022-08-20 02:34 UTC, awiednoor commented
All requested changes were made, enhanced controller and fixed documentation.
Test one last time and if everything is working fine we can merge

2022-08-20 09:53 UTC, khaldarov approved these changes
Very well done, Noor. It looks great.
- ![Screenshot from 2022-08-20 12-36-01](https://user-images.githubusercontent.com/102853969/185740039-5564ed5a-f320-4503-8f8a-a7c77c6ef57e.png)
- ![Screenshot from 2022-08-20 12-36-40](https://user-images.githubusercontent.com/102853969/185740060-91ca5747-e5e1-4062-8a54-112e9aace7b5.png)

2022-08-20 09:53 UTC, khaldarov commented on src/controllers/user.js
>      const User = await UserModel.findById(req.user.userId);
`User` should be camelCased in ALL files; I'm adding this upon Halit's previous request.

2022-08-20 09:53 UTC, khaldarov commented on src/controllers/user.js
> +        message = `${req.body.address.title} Address added`;
`Address` should also be in lowercase. Maybe a "... address has been added"

2022-08-20 09:53 UTC, khaldarov commented on src/controllers/user.js
> +          message = ` ${User.address[addressIndex].title} address has been updated`;
The space at the very first column should be deleted.

2022-08-20 09:53 UTC, khaldarov commented on src/docs/User/updateProfile.yaml
> +          schema:
We might add an enum to make it easier to read.

2022-08-20 09:53 UTC, khaldarov commented on src/docs/User/updateProfile.yaml
> +                  "title": "Home",
They do work, but, we might add a `"Country": "",` empty string here to make sure they work.

2022-08-20 09:53 UTC, khaldarov commented on src/middleware/updateValidation.js
> +        errorsArray.push(`${field} is required in Address`);
`Address` should be lowercased.

2022-08-20 09:53 UTC, khaldarov commented on src/controllers/user.js
> +      if (req.body.address !== null && req.body.address !== undefined) {
We can improve this later to extract the address directly from the `req.body`, and not from the `req.body.address`.

2022-08-20 15:30 UTC, merged