Enhance /register endpoint
RCDD-202203-TUR-BEW/backend-capstone-turkey-lets-share pull request #68
Opened 2022-08-20 22:02 UTC by khaldarov

- Fixes #66.
- Fixes test cases accordingly.
- Changes some `errors` fields to `error`.

2022-08-22 14:04 UTC, khatibAmjad requested changes

2022-08-22 14:04 UTC, khatibAmjad commented on src/controllers/auth.js
> +    const usedPhone = await UserModel.findOne({ phoneNumber });
Can you check for the email and the phone number in one query instead of searching the database twice?

2022-08-22 19:04 UTC, khaldarov commented on src/controllers/auth.js
> +    const usedPhone = await UserModel.findOne({ phoneNumber });
That would make a confusion, I believe, since only 1 query will not tell which one, of `email` and `phoneNumber`, is the already occupied field.

2022-08-24 11:50 UTC, halitbatur approved these changes

2022-08-24 11:51 UTC, khatibAmjad approved these changes

2022-08-24 12:21 UTC, merged