Changes necessary for the front-end design
RCDD-202203-TUR-BEW/backend-capstone-turkey-lets-share pull request #69
Opened 2022-08-20 23:11 UTC by khaldarov

### Might still require some changes; please check you if your previous work does comply with the new version's rules.

 - Fixes `userSchema`.
- Fixes `productSchema`.
- Fixes `register` and documentation.
- Fixes `addNewProduct` and documentation.
- Fixes a bug that prevented products of a deleted user to be automatically deleted.

2022-08-23 16:12 UTC, khatibAmjad requested changes

2022-08-23 16:12 UTC, khatibAmjad commented on src/models/product.js
> +      defauult: 'Donate',
typo here

2022-08-24 10:58 UTC, halitbatur commented
@khaldarov can we get this fixed so that we can merge it

2022-08-24 11:48 UTC, khatibAmjad approved these changes

2022-08-24 12:59 UTC, okurezgi approved these changes

2022-08-24 13:01 UTC, awiednoor approved these changes
Great work Adnan

2022-08-24 13:01 UTC, awiednoor commented on src/controllers/auth.js
so now we don't have these fields when registering, but they can be kept during updating the user? or are we removing them from everywhere?

2022-08-24 13:07 UTC, khaldarov commented on src/controllers/auth.js
We do not require them when registering, but users can add them later on if they want. It also might be kept as only a BE feature.

2022-08-24 13:08 UTC, merged